agi_logger:
  verbosity: INFO
  logger:
    bag_path: /workspaces/logging/test_bags/after_fix_1_and_2
    topics:
    - /drone0/livox/lidar
    - /drone0/livox/imu
    - /camera/camera/color/image_raw/compressed
    - /camera/camera/color/camera_info
    - /drone0/camera/image/compressed
    - /drone0/camera/camera_info
    - /drone0/px4_imu
    - /drone0/adaptive_lio/state/odom
    - /drone0/adaptive_lio/odometry_path
    - /drone0/adaptive_lio/scan
    - /fmu/out/vehicle_gps_position
    - /tf
    - /tf_static
    name: forrest_test_1
    max_bag_size: 1
    override_qos: false
    qos_settings: cfg/qos_profiles.yaml
    compress: true
    duration: 10
    mcap: true
    read_ahead_queue_size: 10000
    max_cache_size: 104857600
    auto_start: true
    auto_start_behavior: toggle_arm
    auto_start_topic: /drone0/platform/info
  tcp_file_communication:
    mode: ask
    server:
      port: 6000
      file_path: /workspaces/logging/bags/agi_log_20260128_115034_climb_test
      host: 0.0.0.0
    client:
      host: 192.168.0.85
      port: 6000
      destination_path: /workspaces/logging/test_recieve
